# Debian based
ARG JAVA_MAJOR_VERSION=8
FROM openjdk:${JAVA_MAJOR_VERSION}-jre-slim

ARG HADOOP_VERSION="3.2.0"
ENV HADOOP_VERSION "${HADOOP_VERSION}"

ARG SPARK_VERSION
ENV SPARK_VERSION "${SPARK_VERSION}"

ENV HADOOP_HOME "/opt/hadoop"
ENV SPARK_HOME "/opt/spark"

RUN set -xeu; \
    # Setup and install
    if [ -z "${HADOOP_VERSION}" ]; then \
        echo "Please set --build-arg HADOOP_VERSION for Docker build!" >&2; \
        sh -c "exit 1"; \
    fi; \
    if [ -z "${SPARK_VERSION}" ]; then \
        echo "Please set --build-arg SPARK_VERSION for Docker build!" >&2; \
        sh -c "exit 1"; \
    fi; \
    ## Hadoop env var
    export HADOOP_NAME="hadoop-${HADOOP_VERSION}"; \
    export HADOOP_DIR="/opt/${HADOOP_NAME}"; \
    export HADOOP_DIR_PARENT="$(dirname "${HADOOP_HOME}")"; \
    mkdir -p ${HADOOP_DIR_PARENT}; \
    ## Spark env var
    export SPARK_NAME="spark-${SPARK_VERSION}-bin-without-hadoop"; \
    export SPARK_DIR="/opt/${SPARK_NAME}"; \
    export SPARK_DIR_PARENT="$(dirname "${SPARK_HOME}")"; \
    mkdir -p ${SPARK_DIR_PARENT}; \
    # Build-time only deps
    apt-get update; \
    apt-get install -y --no-install-recommends \
        wget; \
    # Hadoop installation
    wget -q https://www-us.apache.org/dist/hadoop/common/hadoop-${HADOOP_VERSION}/${HADOOP_NAME}.tar.gz; \
    tar zxf ${HADOOP_NAME}.tar.gz -C ${HADOOP_DIR_PARENT}; \
    :

RUN set -xeu; \
    export HADOOP_NAME="hadoop-${HADOOP_VERSION}"; \
    export HADOOP_DIR="/opt/${HADOOP_NAME}"; \
    export HADOOP_DIR_PARENT="$(dirname "${HADOOP_HOME}")"; \
    export SPARK_NAME="spark-${SPARK_VERSION}-bin-without-hadoop"; \
    export SPARK_DIR="/opt/${SPARK_NAME}"; \
    export SPARK_DIR_PARENT="$(dirname "${SPARK_HOME}")"; \
    rm ${HADOOP_NAME}.tar.gz; \
    ln -s ${HADOOP_DIR} ${HADOOP_HOME}; \
    # Spark installation
    wget -q https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/${SPARK_NAME}.tgz; \
    tar zxf ${SPARK_NAME}.tgz -C ${SPARK_DIR_PARENT}; \
    rm ${SPARK_NAME}.tgz; \
    ln -s ${SPARK_DIR} ${SPARK_HOME}; \
    # Remove unnecessary build-time only dependencies
    apt-get remove -y wget; \
    rm -rf /var/lib/apt/lists/*; \
    :

ENV PATH "${PATH}:${HADOOP_HOME}/bin:${PATH}:${SPARK_HOME}/bin"
